@IsTest
private class ProductReviewTriggerTest {

    @TestSetup
    static void makeData() {
        // Create matching mock product
        Product2 testProd = new Product2(Name = 'Enterprise Cloud Server', IsActive = true, ProductCode = 'ECS-01');
        insert testProd;
    }

    @IsTest
    static void testReviewAnalysisWithRealisticData() {
        // Retrieve the static resource generated by your Node.js engine
        StaticResource sampleDataJson = [SELECT Body FROM StaticResource WHERE Name = 'GeneratedMockData' LIMIT 1];
        String jsonContent = sampleDataJson.Body.toString();
        
        Test.startTest();
        // Deserialize the realistic LLM-generated arrays to fulfill your arrays inside test classes
        Map<String, Object> parsedResults = (Map<String, Object>) JSON.deserializeUntyped(jsonContent);
        List<Object> reviewList = (List<Object>) parsedResults.get('reviews');
        
        List<Product_Review__c> reviewsToInsert = new List<Product_Review__c>();
        Product2 targetProd = [SELECT Id FROM Product2 LIMIT 1];
        
        for(Object rawReview : reviewList) {
            Map<String, Object> reviewMap = (Map<String, Object>) rawReview;
            
            Product_Review__c review = new Product_Review__c();
            review.Product__c = targetProd.Id; // Swap out mock ID with valid transaction ID
            review.Rating__c = (Decimal) reviewMap.get('Rating__c');
            review.Reviewer_Email__c = (String) reviewMap.get('Reviewer_Email__c');
            review.Title__c = (String) reviewMap.get('Title__c');
            review.Review_Body__c = (String) reviewMap.get('Review_Body__c');
            
            reviewsToInsert.add(review);
        }
        
        insert reviewsToInsert;
        Test.stopTest();
        
        System.assertEquals(5, [SELECT COUNT() FROM Product_Review__c], 'Should have inserted all realistic reviews successfully.');
    }
}
